export const CREATE_APPOINTMENT_REQUEST = "CREATE_APPOINTMENT_REQUEST";
export const CREATE_APPOINTMENT_SUCCEED = "CREATE_APPOINTMENT_SUCCEED";
export const CREATE_APPOINTMENT_FAILED = "CREATE_APPOINTMENT_FAILED";
