export const GET_CHANNELS_LIST_REQUEST = "GET_CHANNELS_LIST_REQUEST";
export const GET_CHANNELS_LIST_SUCCEED = "GET_CHANNELS_LIST_SUCCEED";
export const GET_CHANNELS_LIST_FAILED = "GET_CHANNELS_LIST_FAILED";
