export const GET_CHANNELS_LIST_REQUEST = "GET_CHANNELS_LIST_REQUEST";
export const GET_CHANNELS_LIST_SUCCEED = "GET_CHANNELS_LIST_SUCCEED";
export const GET_CHANNELS_LIST_FAILED = "GET_CHANNELS_LIST_FAILED";

export const GET_SINGLE_CHANNEL_REQUEST = "GET_SINGLE_CHANNEL_REQUEST";
export const GET_SINGLE_CHANNEL_SUCCEED = "GET_SINGLE_CHANNEL_SUCCEED";
export const GET_SINGLE_CHANNEL_FAILED = "GET_SINGLE_CHANNEL_FAILED";

export const CREATE_CHANNEL_REQUEST = "CREATE_CHANNEL_REQUEST";
export const CREATE_CHANNEL_FAILED = "CREATE_CHANNEL_FAILED";

export const DELETE_CHANNEL_REQUEST = "DELETE_CHANNEL_REQUEST";
export const DELETE_CHANNEL_SUCCEED = "DELETE_CHANNEL_SUCCEED";
export const DELETE_CHANNEL_FAILED = "DELETE_CHANNEL_FAILED";

export const UPDATE_CHANNEL_REQUEST = "UPDATE_CHANNEL_REQUEST";
export const UPDATE_CHANNEL_SUCCEED = "UPDATE_CHANNEL_SUCCEED";
export const UPDATE_CHANNEL_FAILED = "UPDATE_CHANNEL_FAILED";

export const GET_ALL_CHANNELS_LIST_REQUEST = "GET_ALL_CHANNELS_LIST_REQUEST";
export const GET_ALL_CHANNELS_LIST_SUCCEED = "GET_ALL_CHANNELS_LIST_SUCCEED";
export const GET_ALL_CHANNELS_LIST_FAILED = "GET_ALL_CHANNELS_LIST_FAILED";