export const GET_CHANNELS_LIST_REQUEST = "GET_CHANNELS_LIST_REQUEST";
export const GET_CHANNELS_LIST_SUCCEED = "GET_CHANNELS_LIST_SUCCEED";
export const GET_CHANNELS_LIST_FAILED = "GET_CHANNELS_LIST_FAILED";

export const GET_SINGLE_CHANNEL_REQUEST = "GET_SINGLE_CHANNEL_REQUEST";
export const GET_SINGLE_CHANNEL_SUCCEED = "GET_SINGLE_CHANNEL_SUCCEED";
export const GET_SINGLE_CHANNEL_FAILED = "GET_SINGLE_CHANNEL_FAILED";
