export const GET_DOCTORS_LIST_REQUEST = "GET_DOCTORS_LIST_REQUEST";
export const GET_DOCTORS_LIST_SUCCEED = "GET_DOCTORS_LIST_SUCCEED";
export const GET_DOCTORS_LIST_FAILED = "GET_DOCTORS_LIST_FAILED";
