export const GET_HOSPITALS_LIST_REQUEST = "GET_HOSPITALS_LIST_REQUEST";
export const GET_HOSPITALS_LIST_SUCCEED = "GET_HOSPITALS_LIST_SUCCEED";
export const GET_HOSPITALS_LIST_FAILED = "GET_HOSPITALS_LIST_FAILED";

export const GET_SPECIALIZATION_LIST_REQUEST = "GET_DOCTORS_LIST_REQUEST";
export const GET_SPECIALIZATION_LIST_SUCCEED = "GET_DOCTORS_LIST_SUCCEED";
export const GET_SPECIALIZATION_LIST_FAILED = "GET_DOCTORS_LIST_FAILED";

